### PR TITLE
Updated FavIcons

### PR DESCRIPTION
**Pull request by the-hotmann**
Added all Versions of all available FavIcons.
Also Added normal FavIcons additionally to the apple ones.
Also added the "msapplication-TileImage" meta for Microsoft.

### CODE REVIEW

**Comment by the-hotmann** [comment]
If you give me the original File (EPS, AI or SVG) I will also add the .svg File (FireFox can use it)
And will generate optimized PNGs (the one you use now are not optimized)

**Comment by the-hotmann** [comment]
Size | Name | Purpose
-- | -- | --
32×32 | icon-32.png | Standard for most desktop browsers
128×128 | icon-128.png | Chrome Web Store icon & Small Windows 8 Star Screen Icon*
152×152 | icon-152.png | iPad touch icon (Change for iOS 7: up from 144×144)
167×167 | icon-167.png | iPad Retina touch icon(change for iOS 10: up from 152×152, not in action. iOS 10 will use 152×152)
180×180 | icon-180.png | iPhone Retina
192×192 | icon-192.png | Google Developer Web App Manifest Recommendation
196×196 | icon-196.png | Chrome for Android home screen icon

These sizes should **at least** be available.
All others are just optional. 

We are missing: 
32×32
167×167
180×180
196×196

**Comment by acelaya** [comment]
Wow, thanks for the fix!

Unfortunately there's no "original" file (I'm not that good with design tools 😅), but maybe you can find something useful in [shlink-art](https://github.com/shlinkio/shlink-art).

For example, here is a bigger image which I'm almost sure I originally used to generate favicons https://github.com/shlinkio/shlink-art/blob/master/shlink-logo-blue.png

Maybe you can rescale that down.

Also, I would keep the `10x10` format in icon filenames, mainly because that's the format used in the manifest.json file. If some client has that file cached, they will start to get 404 when trying to load icons.

**Comment by the-hotmann** [comment]
I will open a New Pullrequest with the vectorised Logos & new Logos/FavIcons.
But I would not recommend you to keep the 10x10 (there is not 10x10?) maybe you mean the 16x16?
Also this one you should not use anymore. But you are free to do so, its your App

#EDIT: created the Pullrequest --> https://github.com/shlinkio/shlink-art/pull/1
Its is just adding vectorised Logo ([LINK](https://github.com/MartinH0/shlink-art/blob/704bf4e5d16d970f49a7913af001ca71ccc624c8/shlink-logo-blue%20(vectorised)/shlink-logo-blue.svg)) and a lot of different FavIcons.
Accept them. You can still just use the ones you want.

Pls replace all old FavIcons as my one are highly optimized/compressed, so they are much smaller then the old ones!

**Comment by acelaya** [comment]
Thanks for the amazing work @MartinH0. I'm not really good at the "design" part, so it's much appreciated.

I have merged the other PR, so feel free to add anything from there to shlink-web-client (either by updating this PR or creating a new one, up to you).

By the way, when I said "I would keep the 10x10 format in icon filenames", I didn't mean the 10x10 specifically :sweat_smile:. I was talking about the filename pattern, so for example, instead of having files like `public/icons/icon-72.png`, have `public/icons/icon-72x72.png`.

I'm proposing that because that's how they are currently referenced in the `manifest.json`: https://github.com/shlinkio/shlink-web-client/blob/master/public/manifest.json#L10, so keeping the names would keep those references working for those clients that have cached the manifest file.

Other than that, you clearly know what you are doing here, so I trust you to decide which are the sizes that make sense :smile:

**Comment by the-hotmann** [comment]
Pls note the commit which did not pass "Scrutinizer" it is becasue it canceled, it did not encounter any errors! So should be safe to merge

**Comment by acelaya** [comment]
Thanks for the hard work! :muscle:

**Pull request merged**
