### PR TITLE
Ensure nginx serve SPA on all path

### LINKED ISSUE #155: The official docker build failed to configure nginx with SPA specific settings
Currently if a user try to refresh or visit the page for a specific server directly, for example:
https://example.com/server/455c8f83-42da-47eb-85b1-8992dadf388a/list-short-urls/1

A 404 not found page will be served because nginx is looking for path `/server/455c8f83-42da-47eb-85b1-8992dadf388a/list-short-urls` with the file `1` in it.

Nginx configuration should be changed in order to address this.

### PR DESCRIPTION
**Pull request by Haocen**
closes: #155

### CODE REVIEW

**Comment by acelaya** [comment]
I'm not really sure this is the best approach to solve this. For me, it has the next problems:

* The use of `sed` does not clearly expose the intention, since the regexp is quite complex.
* This change, in the way you did it, has a side effect. The app will no longer return a 404 when fetching an invalid resource, hiding other problems when accidentally introducing typos and such.

My proposal is the next:

Thr project has a `config` directory. Inside of it, create a new one called `docker`, and in there, create an `nginx.conf` file with the next contents:

```nginx
server {
    listen 80 default_server;
    charset utf-8;
    root /usr/share/nginx/html;
    index index.html;

    # When requesting static paths with extension, try them, and return a 404 if not found
    location ~ .+\.(css|js|html|png|jpg|jpeg|gif|bmp|ico|csv|otf|eot|svg|svgz|ttf|woff|woff2|ijmap|pdf|tif|map) {
        try_files $uri $uri/ =404;
    }

    # When requesting a path without extension, try it, and return the index if not found
    # This allows HTML5 history paths to be handled by the client application
    location / {
        try_files $uri $uri/ /index.html$is_args$args;
    }
}
```

This is a copy from the default nginx config but with two improvements:

* It handles paths with extension as static files, making a 404 to be returned if not found.
* It handles any other path in a way that, if not found, it falls back to the `index.html`, solving the originally reported issue.

After that, you need to update the `Dockerfile`, including these changes:

```diff
- RUN rm -r /usr/share/nginx/html
+ RUN rm -r /usr/share/nginx/html && rm /etc/nginx/conf.d/default.conf
+ COPY config/docker/nginx.conf /etc/nginx/conf.d/default.conf
```

And finally, I would also ask you to add this fix to the changelog, linking to the issue #155 

How does this sound?

**Comment by Haocen** [comment]
Sounds good, spinning up a box for testing.

**Comment by acelaya** [comment]
Hey @Haocen, thanks a lot for reporting this and the effort on trying to fix it, but I have just pushed the fix to another PR https://github.com/shlinkio/shlink-web-client/pull/159

It's just the last task missing to publish the new release, and I have now some time to do it.

Sorry I couldn't merge yours.

**Comment by Haocen** [comment]
Np, glad it had been fixed.

**Pull request closed without merging**
