### PR TITLE
Remove dependency on uuid package, and use crypto.randomUUID() instead

### PR DESCRIPTION
**Pull request by acelaya**

### CODE REVIEW

**Comment by chaos95** [comment]
Unfortunately this has broken my local self-hosted instance that is running on HTTP, as the crypto API is not available on non-HTTPS sites.

**Comment by acelaya** [comment]
> Unfortunately this has broken my local self-hosted instance that is running on HTTP, as the crypto API is not available on non-HTTPS sites.

Is there a good reason for you to not use HTTPS?

Most cloud providers have services to automatically generate certificates for free, and for any other case, there's Let's Encrypt.

Not using HTTPS these days is an unjustified liability.

**Comment by chaos95** [comment]
> > Unfortunately this has broken my local self-hosted instance that is running on HTTP, as the crypto API is not available on non-HTTPS sites.
> 
> Is there a good reason for you to not use HTTPS?

This is entirely internal to our office, behind a firewall, and using a custom TLD. Admittedly a pretty niche use-case.

> Most cloud providers have services to automatically generate certificates for free, and for any other case, there's Let's Encrypt.

As described above, we use a custom TLD, which precludes the use of public cert registries. I could deploy a CA locally but that's a lot of extra infra that I was hoping to avoid 😅 

> Not using HTTPS these days is an unjustified liability.

Agreed.

I've worked around the issue on our end by pinning our shlink-web-client to 4.1.2, which works just fine for our needs.

All in all, it's a pretty minor issue, and a very limited use-case, so it's probably not worth your time or mine to fix or change it - but it might be worth mentioning in the docs for shlink and the shlink-web-client that both will need to be HTTPS in order for the web client to be used (since you can't use the HTTPS web client to manage an HTTP shlink instance).

Thanks for developing a great tool by the way! It's light years beyond the other link shorteners I've looked at, and the deployment story (legacy HTTP servers aside 😛 ) is excellent. 

In particular, thank you for adopting `_FILE` config vals so we can use docker secrets easily! That's been a source of frustration for me with a few other services.

**Comment by acelaya** [comment]
Even though I have mixed feelings, this is probably an unintended breaking change, so I'll roll it back and consider it again for v5.

**Pull request merged**
