### PR TITLE
Default sort short URLs list by Created at DESC, fix incorrect order by indicator when no order by specified

### LINKED ISSUE #150: Default sort short URLs list by Created at DESC
When listing the short URLs, default to order by most recently created on the top.

### LINKED ISSUE #151: Bug: When no order is specified, the order by indicator(triangle) still indicate ASC on column
When clicking on a column header a third time, the order by field in request is cleared, but the column header still indicate the column is sorted by ASC order.

### PR DESCRIPTION
**Pull request by Haocen**
closes: https://github.com/shlinkio/shlink-web-client/issues/151
closes: https://github.com/shlinkio/shlink-web-client/issues/150

### CODE REVIEW

**Comment by acelaya** [comment]
I would prefer if you provided two separated PR for every issue.

Mainly because the one reported in #151 is clearly a bug that needs to be fixed, but the other one changes the behavior, and I would prefer to keep it as it is now.

Could you provide a PR for #151 only? I will provide some feedback there.

**Comment by acelaya** [comment]
I'm reading my message again and just realized that I didn't thank you for the effort on opening a pull request :smiley:

By closing this one I don't mean that it is not appreciated. I will be more than glad to merge another pull request.

**Comment by Haocen** [comment]
No problem, I should thank you for making such a great project.

Please allow me some time to make another pull request, my testing system is built on top of AWS spot instances, for whatever reason they took almost half an hour to reserve one today.

**Comment by acelaya** [comment]
Sure! Whenever you can.

**Pull request closed without merging**
