### PR TITLE
Update nginx base image

### PR DESCRIPTION
**Pull request by Starbix**

### CODE REVIEW

**Comment by acelaya** [comment]
This docker image does not seem to exist, which makes the build fail.

**Comment by acelaya** [comment]
I will accept the PR when the image exists.

**Comment by Starbix** [comment]
The tag now exists

**Comment by acelaya** [comment]
Can you rebase your branch from `master` and push again?

**Comment by acelaya** [comment]
This is weird. I think something went wrong with the reabse (in fact it looks more like some kind of merge). There are a lot of changes in the PR which are already in master. I don't know why does it mark them as new.

Could you please open a new PR with a clean branch created from master? I'm not sure if something could break if I merge this one.

**Pull request closed without merging**
